

386_OBJECTS=\
 $(OBJ_PATH)\$O\kbfiltr.obj \
 $(OBJ_PATH)\$O\rawpdo.obj \


_RES_FILE=$(OBJ_PATH)\$O\kbfiltr.res



# lowercased
BASEDIR=c:\winddk\7600.16385.0
OBJECT_ROOT=c:\winddk\7600.16385.0
MAKEDIR_LOWERCASE=c:\winddk\7600.16385.0\src\input\kbfiltr\sys
MAKEDIR_RELATIVE_TO_BASEDIR=src\input\kbfiltr\sys
OBJ_PATH=c:\winddk\7600.16385.0\src\input\kbfiltr\sys
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
